// demo/vue/vite-project/src/App.vue
<script setup lang="ts">

import { useForm } from "./demoNew"
import TemplifyForm from "./components/TemplifyForm.vue"
import { ElButton } from "element-plus";
import { useLanguage } from "./hooks/useLanguage";
import { ElNotification } from "element-plus";
const { formData, formTemplate, isValid, enableAutoValidate, setError, reset, errors } = useForm()
//监听formData
enableAutoValidate()

function submit() {
	ElNotification.success({
		title: 'Success',
		message: JSON.stringify(formData),
		duration: 2000
	})
}

function clear() {
	reset({})
}

function showErrors() {
	ElNotification.error({
		title: 'Error',
		message: JSON.stringify(errors.value),
		duration: 2000
	})
}
const { setLocale } = useLanguage()

</script>

<template>
	<div class="demo-container">
		<templify-form :template="<any>formTemplate" :form-data="formData"></templify-form>
		<div class="buttonsWrapper">
			<label>isValid:</label>
			<el-button size="large" type="primary" :disabled="!isValid" @click="submit">submit</el-button>
			<el-button size="large" type="primary" @click="clear">reset</el-button>
		</div>
		<div class="buttonsWrapper">
			<label>setError:</label>
			<el-button size="large" type="primary" @click="() => setError('code', 'manual error')">setError</el-button>
			<el-button size="large" type="primary" :disabled="isValid" @click="showErrors">errors</el-button>
		</div>
		<div>
			<label>Language: </label>
			<el-button size="large" type="primary" @click="() => setLocale('zh')">中文</el-button>
			<el-button size="large" type="primary" @click="() => setLocale('jp')">日本語</el-button>
			<el-button size="large" type="primary" @click="() => setLocale('en')">English</el-button>
		</div>
	</div>
</template>

<style scoped>
.demo-container {
	width: 500px;
	background-color: #e5e7eb;
	padding: 2em 3em;
	border-radius: 2em;
}

.buttonsWrapper {
	margin-bottom: 1em;

	&>label {
		display: inline-block;
		width: 5em;
	}
}
</style>

// playground/templify-form-playground/src/views/ReactFormView/APP.tsx
import { useForm } from "./hooks"
import { TemplifyForm } from "@/components/TemplifyFormReact/TemplifyFormReact"
import { Button, notification } from "antd"
import { useLanguage } from "@/hooks/useLanguageReact"
import { useCallback, useEffect } from "react"
export function App() {
  const { formData, formTemplate, setField, enableAutoValidate, isValid, setError, reset, errors } = useForm()
  const { setLocale } = useLanguage()
  const [api, contextHolder] = notification.useNotification()

  const submitNotification = useCallback(() => {
    api.open({
      message: "Success",
      description: JSON.stringify(formData),
      type: "success",
      duration: 2000,
    })
  }, [formData])
  const showErrors = useCallback(() => {
    api.open({
      message: "Error",
      description: JSON.stringify(errors),
      type: "error",
      duration: 2000,
    })
  }, [errors])

  const clear = useCallback(() => {
    reset({})
  }, [])
  useEffect(() => {
    enableAutoValidate()
  }, [])
  return (
    <div className="demo-container">
      {contextHolder}
      <TemplifyForm formData={formData} template={formTemplate as any} setField={setField}></TemplifyForm>
      <div>
        <div className="mb-5">
          <label className="inline-block w-30 text-right pr-5 mr-3">isValid</label>
          <Button size="large" type="primary" disabled={!isValid} onClick={submitNotification}>
            submit
          </Button>
          <Button size="large" type="primary" onClick={clear} className="ml-3">
            clear
          </Button>
          <Button size="large" type="primary" onClick={() => reset()} className="ml-3">
            reset
          </Button>
        </div>
        <div className="mb-5 ">
          <label className="inline-block w-30 text-right pr-5 mr-3">setError</label>
          <Button size="large" type="primary" onClick={() => setError("code", "defaultForm.customError")}>
            setError
          </Button>
          <Button className="ml-3" size="large" type="primary" disabled={isValid} onClick={showErrors}>
            errors
          </Button>
        </div>
        <div className="mb-5 ">
          <label className="inline-block w-30 text-right pr-5 mr-3">Language </label>
          <Button size="large" type="primary" onClick={() => setLocale("zh")}>
            中文
          </Button>
          <Button className="ml-3" size="large" type="primary" onClick={() => setLocale("jp")}>
            日本語
          </Button>
          <Button className="ml-3" size="large" type="primary" onClick={() => setLocale("en")}>
            English
          </Button>
        </div>
      </div>
    </div>
  )
}
