// playground/templify-form-playground/src/components/TemplifyForm/TemplifyForm.vue
<script setup lang="ts">

import { ElForm, ElInput, ElFormItem } from "element-plus"
import type { IFormTemplateItem } from "templify-form"
import { useLanguage } from "@/hooks/useLanguage";

interface ITemplifyFormProps<TProps extends string = string, TResolveCxt = any> {
	template: IFormTemplateItem<TProps, TResolveCxt, Record<TProps, any>>[]
	formData: Record<TProps, any>
}
const props = defineProps<ITemplifyFormProps>()
const { t } = useLanguage()


interface ISlots {
	[key: string]: [item: IFormTemplateItem<string, any, any>]
}
defineSlots<ISlots>()
</script>

<template>
	<div role="templify-form-demo" class="size-full">
		<ElForm>
			<template v-for="item of props.template" :key="item.prop">
				<template v-if="item.render">
					<component :is="item.render(item, formData, t)"></component>
				</template>
				<template v-else>
					<slot :name="item.prop" :item=item>
						<ElFormItem :prop="item.prop" :error="item.error.resolve({ t })"
							:class="item.formItemClassName">
							<template v-slot:label>
								<span :class="item.formItemLabelClassName">{{ item.label.resolve({ t }) }}</span>
							</template>
							<ElInput size="large" v-model="formData[item.prop]" :class="item.formItemContentClassName">
							</ElInput>
						</ElFormItem>
					</slot>
				</template>
			</template>
		</ElForm>
	</div>
</template>

<style lang="less" scoped></style>

// demo/react/vite-project/src/components/TemplifyForm.tsx
import { IFormTemplateItem } from "../../../../../types/templify-form"
import { I18nResolveCxt } from "index"
import { Fragment, useEffect, useState } from "react"
import { Form, Input } from "antd"
import { useLanguage } from "@/hooks/useLanguage"

interface ITemplifyFormProps<TProps extends string = string, TResolveCxt = any, TFormData extends Record<TProps, any> = any> {
  template: IFormTemplateItem<TProps, TResolveCxt, TFormData>[]
  formData: Record<TProps, any>
  setField: (key: TProps, value: any) => void
}
export function TemplifyForm<TProps extends string = string, TResolveCxt extends I18nResolveCxt = any, TFormData extends Record<TProps, any> = any>({
  template,
  formData,
  setField,
}: ITemplifyFormProps<TProps, TResolveCxt, TFormData>) {
  const [canRender, setCanRender] = useState(false)
  const { t } = useLanguage()
  useEffect(() => {
    setCanRender(true)
  }, [])
  return (
    <Form>
      {template.map((item) => {
        if (item.render && canRender) {
          // 自定义渲染
          return <Fragment key={item.prop}>{item.render(item, formData as any, t, setField)}</Fragment>
        }
        return (
          <Form.Item
            key={item.prop}
            label={<span className={item.formItemLabelClassName}>{item.label.resolve({ t } as TResolveCxt)}</span>}
            help={item.error.resolve({ t } as TResolveCxt)}
            validateStatus={item.error.resolve({ t } as TResolveCxt) ? "error" : ""}
            className={item.formItemClassName}
          >
            <Input size="large" value={formData[item.prop]} onChange={(e) => setField(item.prop, e.target.value)} className={item.formItemContentClassName} />
          </Form.Item>
        )
      })}
    </Form>
  )
}
